### ISSUE TITLE
modifier is not tracked

### ISSUE THREAD

**Issue by maki5** [mongoid/mongoid-history#116]
I have a problem with modifier, sometimes it's updated with user sometime it's blank, all this can happen on the same record. I tried to add an after_save callback to history_tracker class to set the modifier manually form current_user but seems like it's not triggering this callback

**Comment by jakubstraka** [comment]
Hi, 

I have the same problem. I'm using the tracker in RoR engine with Mongoid::Userstamp. 

I've tried

```Mongoid::History.modifier_class_name = 'MyEngine::User' ```

but didn't help. User or Modifier is not passed in params when I check console. But ```updated_by_id``` is.

But this does work from console

```
user = MyEngine::User.first
page = MyEngine::Page.create(title: 'Test', user: user)
```

and then every update is tracked with the same modifier, even if it's updated by different user.

Any ideas?

Thanks!
J

**Comment by dblock** [comment]
This should be `MyEngine::Page.create(title: 'Test', updated_by: user)`.

**Comment by dblock** [comment]
This is old, closing. Please reopen if you can reproduce.
