### ISSUE TITLE
undo! issues "This should never happen. Please report bug."

### ISSUE THREAD

**Issue by marcocanderle** [mongoid/mongoid-history#168]
Hello, I'm trying mongoid  6.0.0.rc0 with mongoid-history 0.5.1 and after upgrading from mongoid 5, I started to get this weird error message "This should never happen. Please report bug." Hence this ticket. 

First of all, is 0.5.1 the correct branch to use with mongoid 6.0.0.rc0?

Now the issue. 
I have something like what this test shows: https://jpst.it/MlmB
basically, on my project when I try a test similar to that one, when performing this 

`modelone.em1.update_attributes!(name: "new name em1")`
 `modelone.em1.history_tracks.desc(:version).each do |t|
      t.undo! user
    end`

the problem happens on the undo! call when I try to undo the update action. I used to work with mongoid 5 but now with mongoid 6.0.0.rc0 it started to issue that error.

Debugging the issue a lot, I saw the issue is on the traverse_association_chain and what fails in this case is this line: https://github.com/aq1018/mongoid-history/blob/master/lib/mongoid/history/tracker.rb#L203

But if I print "doc.name" right before the error message, it shows the correct document as expected, so there is something definitely wrong when evaluating the embeds_one? method.

I tried the test in the link on the mongoid-history gem specs but was not able to reproduce the error as in my project. So I wanted to ask if someone else has faced this kind of issues and what do you think could be the reason for this.

Any help would be really appreciated!

The gemfile extract is this one:

gem 'rails', '~> 5.0'

gem 'mongoid', '~> 6.0.0.rc0'
gem 'mongoid-slug', github: 'digitalplaywright/mongoid-slug'
gem 'mongoid-history', github: 'aq1018/mongoid-history'
gem 'mongoid_userstamp'
gem 'mongoid_token'
gem 'request_store'
gem 'symmetric-encryption'

**Comment by dblock** [comment]
Use HEAD for 6.0, and maybe try to write a spec for this scenario, please?

**Comment by marcocanderle** [comment]
I did try that already. This link https://jpst.it/MlmB is my attempt, but I was not able to reproduce it there that's why I didn't push a pull request yet. I'll keep trying to reproduce this but wanted to see if someone had had a similar issue or know what this could be about

**Comment by dblock** [comment]
This has been long fixed in 0.8.1.
