### ISSUE TITLE
Deprecation warning extremely noisy and unnecessary

### ISSUE THREAD

**Issue by alauper** [mongoid/mongoid-history#177]
I'm seeing a million deprecation notices throughout my logs.

[DEPRECATION] Use :fields instead of :all to track all fields in class ...
Going forward, :all will track all the fields and relations for the class

So if I'm actually using :all intentionally and the correct way, why am I seeing constant deprecation warnings.  There's nothing in my code to change or update.  Every rails requests seems to display the deprecation warning, sometimes multiple times.

Seems extremely noisy and unnecessary.

**Comment by dblock** [comment]
I think I agree, @JagdeepSingh added that, but it's really a behavior change, not a deprecation. I'd take a PR that removes the message and makes sure UPGRADING says all the right things.

**Comment by sivagollapalli** [comment]
@dblock I removed deprecation notice. But I didn't understand "makes sure UPGRADING says all the right things." . Could you elaborate?

**Comment by alauper** [comment]
I'm using the latest version of mongoid-history and I still see these deprecation notices 6 months later.  They're all over my log files.  Quite obnoxious.

<img width="1043" alt="screen shot 2017-04-20 at 12 17 23 pm" src="https://cloud.githubusercontent.com/assets/822101/25245944/5c41a82e-25c3-11e7-9aba-5867a64f2840.png">

**Comment by dblock** [comment]
@alauper Are you working on finishing https://github.com/mongoid/mongoid-history/pull/180?

**Comment by alauper** [comment]
To be honest, I stopped using this library a while ago because of the deprecation notices.  I'm not currently working on #180.  All the best.
