### ISSUE TITLE
Is it possible to store each model in a diferent collection?

### ISSUE THREAD

**Issue by mateuspontes** [mongoid/mongoid-history#190]
I'd like to store models in collections like this:

```ruby
# /app/models/first_model.rb
class FirstModel
  include Mongoid::Document

  Mongoid::History.tracker_class_name = 'history_first_model'
  include Mongoid::History::Trackable
```

```ruby
# /app/models/second_model.rb
class SecondModel
  include Mongoid::Document

  Mongoid::History.tracker_class_name = 'history_second_model'
  include Mongoid::History::Trackable
```

Problem: sometimes FirstModel data are stored in history_second_model and vice versa.

**Comment by dblock** [comment]
This would be a very useful feature, please contribute!

**Comment by sivagollapalli** [comment]
@dblock Looks like this feature has incorporated. Could you please refer this  `spec/integration/multiple_trackers_spec.rb`. I think we can close this issue.

**Comment by dblock** [comment]
Closing via https://github.com/mongoid/mongoid-history/pull/196
