### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-history#199]
@ojbucao Want to help?

**Comment by dblock** [comment]
We need a RELEASING doc ala https://github.com/mongoid/mongoid-shell/blob/master/RELEASING.md too.

**Comment by mikwat** [comment]
@dblock I'm thinking this release should be tagged 0.7.0 since https://github.com/mongoid/mongoid-history/pull/202 is a borderline breaking change. Thoughts?

**Comment by mikwat** [comment]
Went ahead with 0.7.0, hopefully that was ok!

**Comment by dblock** [comment]
Perfect, thanks.
