### ISSUE TITLE
Unable to Contribute

### ISSUE THREAD

**Issue by dneilroth** [mongoid/mongoid-history#218]
Hello,
I am unable to download the contributor repo mentioned here https://github.com/mongoid/mongoid-history/blob/master/CONTRIBUTING.md and I also do not have permission to push a branch to the main repo here https://github.com/mongoid/mongoid-history.git. Please advise on the best way to contribute, thanks!!

Best

David

**Comment by dblock** [comment]
Replace `contributor` with your username. Please feel free to contribute to the doc if ti's not clear or ask questions here.

Generally follow https://guides.github.com/introduction/flow/.
