### ISSUE TITLE
undefined method `[]' for #<..::EmbedsMany>

### ISSUE THREAD

**Issue by moddx** [mongoid/mongoid-history#219]
I'm trying to use mongoid-history, but I'm confronted with the following error message when trying to save an object. Disabling mongoid-history lets me save my objects just fine.

*undefined method `[]' for #<Mongoid::Association::Embedded::EmbedsMany:0x000055c671c28fe8>*

I am running Rails 5.2.0 on ruby 2.5.1, together with mongoid 7.0.0 and mongoid-history 0.8.0.

Following are my models:
``` ruby
class Recipe
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::History::Trackable

  field :name, type: String
  field :intro, type: String
  field :quantity, type: String
  field :instructions, type: String
  field :tags, type: Array, default: []

  embeds_many :ingredients
  accepts_nested_attributes_for :ingredients, :allow_destroy => true

  track_history on: [:fields, :embedded_relations],
                :modifier_field => :modifier,
                :modifier_field_inverse_of => :nil,
                :version_field => :version,
                :track_create   =>  true,
                :track_update   =>  true,
                :track_destroy  =>  true

  def tags_list=(arg)
    self.tags = arg.split
  end

  def tags_list
    self.tags.join(' ')
  end
end
```

``` ruby
class Ingredient
  include Mongoid::Document
  field :quantity, type: String
  field :unit, type: String
  field :name, type: String
  embedded_in :recipe, :inverse_of => :ingredients
end
```

``` ruby
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :active, type: Mongoid::Boolean
  field :restricted, type: Mongoid::Boolean
  field :avatar, type: BSON::Binary

  has_secure_password
  validates_presence_of :password, :on => :create

  index({ name: 1 }, { unique: true, name: 'name_idx' })
end
```

Doing something like the following results in the above mentioned error:
``` ruby
user = User.first
recipe = Recipe.first
recipe.name = "Something Else"
recipe.modifier = user
recipe.save
``` 

Might just be an configuration issue, but I can't figure out what's wrong.

**Comment by dblock** [comment]
That's probably because support for mongoid 7 hasn't been added. Care to PR it? Start by adding to .travis.yml and seeing what breaks? Also we should lock things down to mongoid `< 8` to avoid similar problems in the future.

**Comment by dblock** [comment]
I opened https://github.com/mongoid/mongoid-history/issues/220 too.

**Comment by dblock** [comment]
Maybe Mongoid7 changed the class names? Check what `relation_of(field)` returns now?

**Comment by dblock** [comment]
Btw, [Donate $50 to my charity](https://runwithtfk.org/Profile/PublicPage/61018) and I can take care of it :)

**Comment by dblock** [comment]
Dup for https://github.com/mongoid/mongoid-history/issues/220, there’s a PR too :)
